spring:
  application:
    name: LibraryFrontend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/library

library:
  backend:
    baseUrl: http://localhost:8081

server:
  port:

logging.level.org.springframework.security: DEBUG

