spring:
  application:
    name: LibraryBackend

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/library
          jwk-set-uri: http://localhost:8085/realms/library/protocol/openid-connect/certs
          jws-algorithms: RS256

  r2dbc:
    url: r2dbc:mysql://localhost:3306/library
    username: admin
    password: pwd
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: always
      platform: mysql

server:
  port: 8081
